name: Update badges

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x mk

      - name: Set up Nix
        uses: cachix/install-nix-action@v27

      - name: Run script inside flake dev shell
        run: nix develop --command ./mk badges

      - name: Commit and push if badges changed
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add assets
          git diff --cached --quiet || git commit -m "Update badges"
          git push
